<div class="showRating">
          <table>
        <thead>
            <tr>
                <th>User</th>
                <th>Rating</th>
                <th>Comment</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        <tr>
        <td>data</td>
          <td>data</td>
          <td>data</td>
          <td>data</td>
        </tr>
        </tbody>
    </table>
      </div>